<?php define('usemainjs',false);define('dotdotcnt',3); define('bodyClass',''); define('titleExtend','Return &amp; Refund Policy');define('footerFixed',false); require_once('./../static/Content/head.php'); ?>
<div class="container-fluid">
    <div class="card">
        <!---->
        <div class="card-title">
            <h1 style="margin-top: 10px;margin-left: 10px;">Return &amp; Refund Policy</h1>
        </div> <div class="tucupampam card-body" style="z-index: 100;"> <p>Updated at 2021-10-11</p> <p class="p6"><br></p> <h1>Definitions and key terms</h1> <p class="p8"><span class="s1">To help explain things as clearly as possible in this Return &amp; Refund Policy, every time any of these terms are referenced, are strictly defined as:</span></p> <p class="p9"><br></p> <ul class="ul1"><!----> <li class="li8"><span class="s1"><strong>Company:</strong> when this policy mentions “Company,” “we,” “us,” or “our,” it refers to <a>Days Web App</a> that is responsible for your information under this Return &amp; Refund Policy.<br></span></li> <li class="li8"><span class="s1"><strong>Customer:</strong> refers to the company, organization or person that signs up to use the  Service to manage the relationships with your consumers or service users.<br></span></li> <li class="li8"><span class="s1"><strong>Device:</strong> any internet connected device such as a phone, tablet, computer or any other device that can be used to visit  and use the services.<br></span></li> <li class="li8"><span class="s1"><strong>Service:</strong> refers to the service provided by <a>Days Web App</a> as described in the relative terms (if available) and on this platform.<br></span></li> <li class="li8"><span class="s1"><strong>Website:</strong> <a>Days Web App</a>’s site, which can be accessed via this URL: <a>nawin.com/days.</a><br></span></li> <li class="li8"><span class="s1"><strong>You:</strong> a person or entity that is registered with <a>Days Web App</a> to use the Services.<br></span></li></ul> <p class="p3"><br></p> <h1>Return &amp; Refund Policy</h1> <p class="p10"><span class="s1">Thanks for shopping at <a>Days Web App</a>. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you’re exploring, evaluating, and purchasing our products.
    <br><br>
As with any shopping experience, there are terms and conditions that apply to transactions at <a>Days Web App</a>. We’ll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at <a>Days Web App</a>, you agree to the terms set forth below along with <a>Days Web App</a>’s&nbsp;Privacy Policy.
    <br><br>
If there’s something wrong with the product you bought, or if you are not happy with it, you have () to issue a refund and return your item.
    <br><br>
If you would like to return a product, the only way would be if you follow the next guidelines:</span></p> <ul class="ul1"><!----> <!----> <!----></ul> <p class="p3"><br></p> <h1>Refunds</h1> <p class="p10"><span class="s1">We at&nbsp;<a>Days Web App</a>&nbsp;commit ourselves to serving our customers with the best products. Every single product that you choose is thoroughly inspected, checked for defects and packaged with utmost care. We do this to ensure that you fall in love with our products.
    <br><br>
Sadly, there are times when we may not have the product(s) that you choose in stock, or may face some issues with our inventory and quality check. In such cases, we may have to cancel your order. You will be intimated about it in advance so that you don't have to worry unnecessarily about your order. If you have purchased via Online payment (not Cash on Delivery), then you will be refunded once our team confirms your request.
<br><br>
We carry out thorough quality check before processing the ordered item. We take utmost care while packing the product. At the same time we ensure that the packing is good such that the items won’t get damaged during transit. Please note that <a>Days Web App</a> is not liable for damages that are caused to the items during transit or transportation.
<br><br>
We will revise your returned product as soon as we receive it and if it follows the guidelines addressed above, we will proceed to issue a refund of your purchase. Your refund may take a couple of days to process but you will be notified when you receive your money.</span></p> <p class="p3"><br></p> <h1>Shipping</h1> <p class="p10"><span class="s1"><a>Days Web App</a> is not responsible for return shipping costs. Every shipping has to be paid by the customer, even if the item had free shipping in the first place, the customer has to pay for the shipping in return.
</span></p> <p class="p3"><br></p> <!----> <!----> <!----> <!----> <!----> <!----><!----><!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <!----> <h1>Your Consent</h1> <p class="p10"><span class="s1">By using our platform, registering an account, or making a purchase, you hereby consent to our Return &amp; Refund Policy and agree to its terms.</span></p> <p class="p3"><br></p> <h1>Changes To Our Return &amp; Refund Policy</h1> <p class="p10"><span class="s1">Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you will be bound by the updated Return &amp; Refund Policy. If you do not want to agree to this or any updated Return &amp; Refund Policy, you can delete your account.</span></p> <p class="p3"><br></p> <h1>Contact Us</h1> <p class="p10"><span class="s1">If, for any reason, You are not completely satisfied with any good or service that we provide, don't hesitate to contact us and we will discuss any of the issues you are going through with our product.</span></p> <ul class="ul1"><li class="li16"><span class="s3">Via Email: <a>zazasvgamekung@hotmail.com, igamesecure@aol.com, contact@nawin.com</a></span></li> <li class="li16"><span class="s3">Via Phone Number: <a>+66988315520</a></span></li> <li class="li16"><span class="s3">Via this Link: <a>https://nawin.com/days/system/contact</a></span></li> <li class="li16"><span class="s3">Via this Address: <a>375 Somdejaopraya Sub-District, Somdejaopraya Road, Klongsan District, Bangkok, Thailand, 10600.</a></span></li></ul></div></div></div>
    <?php require_once('./../static/Content/foot.php'); ?>